### ISSUE TITLE
Scoping breaks foe or ally identifier 

### ISSUE THREAD

**Issue by ISuckM8** [tunbridgep/gmdx-vrsd-fork#33] opened 2024-04-21 11:38 UTC
If you scope with a weapon, in my case the sniper rifle, crossbow won't change from white to red when you aim at enemies.

Possible causes: no clue, it used to work before I believe so maybe you'll know something.

**Comment by tunbridgep** [comment] 2024-04-21 12:17
I believe this is caused by #24. Will need to check more thoroughly

**Comment by tunbridgep** [comment] 2024-04-22 15:23
Fixed by 8ae3aef

**Closed by tunbridgep** 2024-04-22 15:23 UTC
Labels: bug
